// Original synthesized effects, generated by scripts/generate-soundboard.py.
var sounds = [
  {name:"Ping",file:"ping.wav"},
  {name:"Applause",file:"applause.wav"},
  {name:"Air Horn",file:"air-horn.wav"},
  {name:"Rimshot",file:"rimshot.wav"},
  {name:"Drum Roll",file:"drum-roll.wav"},
  {name:"Sad Trombone",file:"sad-trombone.wav"},
  {name:"Level Up",file:"level-up.wav"},
  {name:"Boing",file:"boing.wav"}
]
