use anyhow::{Context, bail};
use std::{
    env,
    path::{Path, PathBuf},
};
use tokio::{fs, process::Command};

const BACKEND: &str = "omarchy_hyprland";
const GENERATED_HEADER: &str = "-- Generated by Wisp. Change this shortcut in Wisp Settings.";
const SHORTCUT_PREFIX: &str = "-- Wisp shortcut: ";
const INCLUDE_BLOCK: &str =
    "-- BEGIN WISP MANAGED PTT\nrequire(\"hypr.wisp\")\n-- END WISP MANAGED PTT";
const MODIFIER_ORDER: [&str; 4] = ["SUPER", "CTRL", "ALT", "SHIFT"];

#[derive(Debug)]
pub struct ShortcutUpdate {
    pub shortcut: Option<String>,
    pub backend: String,
    pub replaced: Vec<String>,
}

#[derive(Debug)]
pub struct ShortcutManager {
    config_dir: PathBuf,
    executable_override: Option<PathBuf>,
    reload: bool,
}

impl ShortcutManager {
    pub fn from_environment() -> Self {
        let configured_dir = env::var_os("WISP_HYPR_CONFIG_DIR").map(PathBuf::from);
        let config_dir = configured_dir.clone().unwrap_or_else(|| {
            env::var_os("XDG_CONFIG_HOME").map_or_else(
                || {
                    env::var_os("HOME")
                        .map_or_else(|| PathBuf::from("."), PathBuf::from)
                        .join(".config/hypr")
                },
                |path| PathBuf::from(path).join("hypr"),
            )
        });
        Self {
            config_dir,
            executable_override: env::var_os("WISP_WISPCTL_PATH").map(PathBuf::from),
            reload: configured_dir.is_none()
                && env::var_os("HYPRLAND_INSTANCE_SIGNATURE").is_some(),
        }
    }

    pub fn backend(&self) -> Option<&'static str> {
        self.bindings_path().is_file().then_some(BACKEND)
    }

    pub async fn load_shortcut(&self) -> Option<String> {
        let contents = fs::read_to_string(self.generated_path()).await.ok()?;
        contents
            .lines()
            .find_map(|line| line.strip_prefix(SHORTCUT_PREFIX))
            .and_then(|shortcut| normalize_shortcut(shortcut).ok())
    }

    pub async fn set(&self, requested: Option<&str>) -> anyhow::Result<ShortcutUpdate> {
        if !fs::try_exists(self.bindings_path()).await? {
            bail!(
                "global shortcut setup currently supports Omarchy/Hyprland; {} was not found",
                self.bindings_path().display()
            );
        }
        let shortcut = requested.map(normalize_shortcut).transpose()?;
        let executable = if shortcut.is_some() {
            Some(self.find_wispctl().context(
                "wispctl is not installed; from the Wisp repository run: just cli-install",
            )?)
        } else {
            None
        };
        let replaced = if let Some(shortcut) = shortcut.as_deref() {
            existing_bindings(shortcut).await
        } else {
            Vec::new()
        };
        let bindings_path = self.bindings_path();
        let generated_path = self.generated_path();
        let original_bindings = fs::read_to_string(&bindings_path)
            .await
            .with_context(|| format!("read {}", bindings_path.display()))?;
        let original_generated = fs::read(&generated_path).await.ok();
        let next_bindings = ensure_include(&original_bindings);
        let generated = render_config(shortcut.as_deref(), executable.as_deref());

        atomic_write(&generated_path, generated.as_bytes()).await?;
        if next_bindings != original_bindings {
            atomic_write(&bindings_path, next_bindings.as_bytes()).await?;
        }
        if self.reload
            && let Err(error) = reload_and_validate().await
        {
            atomic_write(&bindings_path, original_bindings.as_bytes()).await?;
            if let Some(contents) = original_generated {
                atomic_write(&generated_path, &contents).await?;
            } else if fs::try_exists(&generated_path).await? {
                fs::remove_file(&generated_path).await?;
            }
            let _ = reload_and_validate().await;
            return Err(error.context("Hyprland rejected the Wisp shortcut; restored prior config"));
        }

        Ok(ShortcutUpdate {
            shortcut,
            backend: BACKEND.into(),
            replaced,
        })
    }

    fn bindings_path(&self) -> PathBuf {
        self.config_dir.join("bindings.lua")
    }

    fn generated_path(&self) -> PathBuf {
        self.config_dir.join("wisp.lua")
    }

    fn find_wispctl(&self) -> Option<PathBuf> {
        if let Some(path) = self
            .executable_override
            .as_ref()
            .filter(|path| path.is_file())
        {
            return Some(path.clone());
        }
        env::var_os("PATH")
            .into_iter()
            .flat_map(|paths| env::split_paths(&paths).collect::<Vec<_>>())
            .map(|directory| directory.join("wispctl"))
            .find(|path| path.is_file())
    }
}

fn normalize_shortcut(value: &str) -> anyhow::Result<String> {
    let mut modifiers = Vec::new();
    let mut key = None;
    for part in value
        .split('+')
        .map(str::trim)
        .filter(|part| !part.is_empty())
    {
        let part = part.to_ascii_uppercase();
        let canonical = match part.as_str() {
            "SUPER" | "META" => Some("SUPER"),
            "CTRL" | "CONTROL" => Some("CTRL"),
            "ALT" => Some("ALT"),
            "SHIFT" => Some("SHIFT"),
            _ => None,
        };
        if let Some(modifier) = canonical {
            if !modifiers.contains(&modifier) {
                modifiers.push(modifier);
            }
        } else if key.replace(part).is_some() {
            bail!("shortcut must contain exactly one non-modifier key");
        }
    }
    let key = key.context("shortcut must contain a letter, number, or function key")?;
    if !valid_key(&key) {
        bail!("unsupported shortcut key: {key}");
    }
    let mut normalized = MODIFIER_ORDER
        .into_iter()
        .filter(|modifier| modifiers.contains(modifier))
        .collect::<Vec<_>>();
    normalized.push(&key);
    Ok(normalized.join(" + "))
}

fn valid_key(key: &str) -> bool {
    if key.len() == 1 && key.as_bytes()[0].is_ascii_alphanumeric() {
        return true;
    }
    if let Some(number) = key
        .strip_prefix('F')
        .and_then(|value| value.parse::<u8>().ok())
    {
        return (1..=35).contains(&number);
    }
    matches!(
        key,
        "SPACE"
            | "TAB"
            | "RETURN"
            | "ENTER"
            | "BACKSPACE"
            | "DELETE"
            | "HOME"
            | "END"
            | "PAGEUP"
            | "PAGEDOWN"
            | "UP"
            | "DOWN"
            | "LEFT"
            | "RIGHT"
            | "INSERT"
            | "PAUSE"
    ) || key.strip_prefix("XF86").is_some_and(|suffix| {
        !suffix.is_empty() && suffix.chars().all(|ch| ch.is_ascii_alphanumeric())
    })
}

fn ensure_include(bindings: &str) -> String {
    if bindings.contains("require(\"hypr.wisp\")") {
        return bindings.to_owned();
    }
    format!(
        "{}{}{}\n",
        bindings,
        if bindings.ends_with('\n') { "" } else { "\n" },
        INCLUDE_BLOCK
    )
}

fn render_config(shortcut: Option<&str>, executable: Option<&Path>) -> String {
    let Some(shortcut) = shortcut else {
        return format!("{GENERATED_HEADER}\n-- No shortcut is currently set.\n");
    };
    let executable = executable.expect("an executable is required for a configured shortcut");
    let command = shell_quote(&executable.to_string_lossy());
    let shortcut = lua_quote(shortcut);
    let press = lua_quote(&format!("{command} ptt press"));
    let release = lua_quote(&format!("{command} ptt release"));
    format!(
        "{GENERATED_HEADER}\n{SHORTCUT_PREFIX}{shortcut}\nhl.unbind(\"{shortcut}\")\no.bind(\"{shortcut}\", \"Wisp push-to-talk\", \"{press}\")\no.bind(\"{shortcut}\", \"Release Wisp push-to-talk\", \"{release}\", {{ release = true }})\n"
    )
}

fn lua_quote(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

async fn existing_bindings(shortcut: &str) -> Vec<String> {
    let Ok(output) = Command::new("omarchy")
        .args(["menu", "keybindings", "--print"])
        .output()
        .await
    else {
        return Vec::new();
    };
    if !output.status.success() {
        return Vec::new();
    }
    let mut descriptions = String::from_utf8_lossy(&output.stdout)
        .lines()
        .filter_map(|line| line.split_once('→'))
        .filter(|(keys, _)| keys.trim().eq_ignore_ascii_case(shortcut))
        .map(|(_, description)| description.trim().to_owned())
        .filter(|description| {
            !description.starts_with("Wisp push-to-talk")
                && !description.starts_with("Release Wisp push-to-talk")
        })
        .collect::<Vec<_>>();
    descriptions.sort();
    descriptions.dedup();
    descriptions
}

async fn atomic_write(path: &Path, contents: &[u8]) -> anyhow::Result<()> {
    let temporary = path.with_extension("lua.wisp-tmp");
    fs::write(&temporary, contents)
        .await
        .with_context(|| format!("write {}", temporary.display()))?;
    if let Ok(metadata) = fs::metadata(path).await {
        fs::set_permissions(&temporary, metadata.permissions()).await?;
    }
    fs::rename(&temporary, path)
        .await
        .with_context(|| format!("replace {}", path.display()))
}

async fn reload_and_validate() -> anyhow::Result<()> {
    let reload = Command::new("hyprctl").arg("reload").output().await?;
    if !reload.status.success() {
        bail!(
            "hyprctl reload failed: {}",
            String::from_utf8_lossy(&reload.stderr).trim()
        );
    }
    let errors = Command::new("hyprctl").arg("configerrors").output().await?;
    if !errors.status.success() {
        bail!(
            "hyprctl configerrors failed: {}",
            String::from_utf8_lossy(&errors.stderr).trim()
        );
    }
    let errors = String::from_utf8_lossy(&errors.stdout);
    if !errors.trim().is_empty() {
        bail!("Hyprland config error: {}", errors.trim());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{ensure_include, normalize_shortcut, render_config};
    use std::path::Path;

    #[test]
    fn shortcuts_are_normalized_and_restricted() {
        assert_eq!(
            normalize_shortcut("shift + meta + f8").unwrap(),
            "SUPER + SHIFT + F8"
        );
        assert_eq!(normalize_shortcut("F8").unwrap(), "F8");
        assert!(normalize_shortcut("SUPER + SHIFT").is_err());
        assert!(normalize_shortcut("CTRL + A + B").is_err());
        assert!(normalize_shortcut("CTRL + semicolon").is_err());
    }

    #[test]
    fn generated_config_is_scoped_and_included_once() {
        let bindings = ensure_include("-- personal bindings\n");
        assert!(bindings.contains("require(\"hypr.wisp\")"));
        assert_eq!(ensure_include(&bindings), bindings);

        let config = render_config(Some("F8"), Some(Path::new("/home/test/.local/bin/wispctl")));
        assert!(config.contains("hl.unbind(\"F8\")"));
        assert!(config.contains("ptt press"));
        assert!(config.contains("release = true"));
    }
}
